### ISSUE TITLE
axpy.cu grid_dim

### ISSUE THREAD

**Issue by jgphpc** [eth-cscs/SummerSchool2017#10]
Minor issue that may need an update:

In https://github.com/eth-cscs/SummerSchool2017/blob/master/topics/cuda/solutions/axpy/axpy.cu#L41
`grid_dim = (n-1)/block_dim + 1;`
but on slide https://github.com/eth-cscs/SummerSchool2017/blob/master/topics/cuda/kernels.pdf page15, it is: `[ n+(block_size-1) ] / block_size`

It is mathematically identical, hence no issue.

**Comment by rjanalik** [comment]
It might be confusing because it is different in slides and in the code, but the result is the same.

**Comment by jgphpc** [comment]
yes just realized that, sorry !
